import { AICrimeLanguage, getLocalizedAICrimePath } from './aiCrimeData';

export const containmentPath = '/ai-crime-files/ai-agent-containment-failure';
export const containmentImage = '/images/ai-crime-files/ai-agent-containment-failure.webp';
export const containmentCopy: Record<AICrimeLanguage, { title: string; description: string; label: string; read: string; alt: string }> = {
  en: { title: 'AI agent containment failure: lessons from the OpenAI wiki incident', description: 'How read-only access became external writes, shared memory and agent coordination. What the DseWiki incident teaches about harness engineering.', label: 'Technical explainer · Harness Engineering', read: 'Read the analysis', alt: 'Conceptual illustration of connected AI nodes crossing a glass containment boundary to reach a shared external network' },
  pt: { title: 'Falha de contenção de agentes de IA: o caso da wiki da OpenAI', description: 'Como o acesso de leitura permitiu alterações externas, memória compartilhada e coordenação entre agentes. As lições do caso DseWiki para Harness Engineering.', label: 'Análise técnica · Harness Engineering', read: 'Ler a análise', alt: 'Ilustração conceitual de nós de IA conectados atravessando um limite de contenção de vidro até uma rede externa compartilhada' },
  es: { title: 'Fallo de contención de agentes de IA: el caso de la wiki de OpenAI', description: 'Cómo el acceso de lectura permitió escrituras externas, memoria compartida y coordinación entre agentes. Lecciones de DseWiki para Harness Engineering.', label: 'Análisis técnico · Harness Engineering', read: 'Leer el análisis', alt: 'Ilustración conceptual de nodos de IA conectados que cruzan un límite de contención de cristal hacia una red externa compartida' },
  fr: { title: 'Défaillance du confinement des agents IA : le cas du wiki OpenAI', description: 'Comment un accès en lecture a permis des modifications externes et une coordination entre agents. Les leçons de DseWiki pour le Harness Engineering.', label: 'Analyse technique · Harness Engineering', read: 'Lire l’analyse', alt: 'Illustration conceptuelle de nœuds d’IA connectés franchissant une enceinte de verre pour rejoindre un réseau externe partagé' },
  it: { title: 'Contenimento degli agenti IA: cosa insegna il caso wiki di OpenAI', description: 'Come un accesso in lettura ha consentito scritture esterne, memoria condivisa e coordinamento tra agenti. Lezioni di DseWiki per Harness Engineering.', label: 'Analisi tecnica · Harness Engineering', read: 'Leggi l’analisi', alt: 'Illustrazione concettuale di nodi IA collegati che attraversano una barriera di vetro verso una rete esterna condivisa' },
  ja: { title: 'AIエージェントの封じ込め失敗：OpenAIのWiki事案から学ぶ', description: '読み取り専用のはずのアクセスが外部への書き込みとエージェント間の連携につながった理由。DseWiki事案から実行基盤の設計を考える。', label: '技術解説 · Harness Engineering', read: '解説を読む', alt: 'ガラスの封じ込め境界を越えて外部の共有ネットワークにつながるAIノードを表した概念イラスト' },
};

export const containmentHref = (language: AICrimeLanguage) => getLocalizedAICrimePath(containmentPath, language);
